version: '3'
services:
  server:
    restart: always
    build: .
    ports:
      - "5000:5000"
    container_name: 'jpbank-coin-handling-fee-simulator-api-server'
    tty: true
    volumes:
      - .:/app